language: ruby
rvm:
  - 1.9.3
install:
  - echo '"install" phase'
script:
  - export VEEWEEBOT_DEPLOY_FILE=binaryfile.blob
  - export VEEWEEBOT_DEPLOY_BUILD_TIMESTAMP=`date`
  - export VEEWEEBOT_DEPLOY_FILE_CONTENT_TYPE=application/octet-stream
  - export VEEWEEBOT_DEPLOY_BUILD_URL=http://travis-ci.org/veewee-community/veeweebot/builds/$TRAVIS_BUILD_ID
  - ./deploy.sh
env:
  global:
    - secure: "hFZemFQ58B8AAxmGKZVB6plUY6Hwgj18Kmv5uP313CD/RU2+5nz3VpIDKlXt\nun6Jnmf+K5njitLsL1/n7VyXTItC+lX/kXwC4UF4Te5lOi7wOMhrPBG28GOE\nN+y3mJRhtaUXevaTzR98sq7klS+4eJMIli3xSNHABELhSBzmAHg="
