language: ruby
rvm:
  - 1.9.3
install:
  - echo '"install" phase'
script:
  - export VEEWEEBOT_DEPLOY_REPO_USERNAME=`echo \`cd .. && echo ${PWD##*/}\``
  - export VEEWEEBOT_DEPLOY_REPO_NAME=`echo ${PWD##*/}`
  - export VEEWEEBOT_DEPLOY_FILE=binaryfile.blob
  - export VEEWEEBOT_DEPLOY_OAUTH_USERNAME=veeweebot
  - ./deploy.sh
env:
  global:
    - secure: "hFZemFQ58B8AAxmGKZVB6plUY6Hwgj18Kmv5uP313CD/RU2+5nz3VpIDKlXt\nun6Jnmf+K5njitLsL1/n7VyXTItC+lX/kXwC4UF4Te5lOi7wOMhrPBG28GOE\nN+y3mJRhtaUXevaTzR98sq7klS+4eJMIli3xSNHABELhSBzmAHg="