language: ruby
rvm:
  - 1.9.3
install:
  - echo '"install" phase'
script:
  - export VEEWEEBOT_DEPLOY_REPO_USERNAME=`echo \`cd .. && echo ${PWD##*/}\``
  - export VEEWEEBOT_DEPLOY_REPO_NAME=`echo ${PWD##*/}`
  - export VEEWEEBOT_DEPLOY_FILE=$VEEWEEBOT_DEPLOY_REPO_NAME.box
  - export VEEWEEBOT_DEPLOY_OAUTH_USERNAME=veeweebot_username
  - export VEEWEEBOT_DEPLOY_OAUTH_TOKEN=veeweebot_token
  - ./deploy.sh